config/routes.rb
Rails.application.routes.draw do

  get 'payment_notification/create'

  get 'site/about'
  get 'site/contact'

 
  get '/about' => 'site#about' 
  get '/contact' => 'site#contact'

  get '/admin' => 'user#admin_login'
  get '/logout' => 'user#logout'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  resources :profiles
  devise_for :users

  resources :products
  resources :order_items
  resource :carts, only: [:show] 
  resource :payments, only: [:show]
  resource :thankyous, only: [:show]
  delete '/carts' => 'carts#destroy'
  get '/carts/index' => 'carts#index'
  
  #resources :payment_notification, only: [:create]
  get '/profile/show'=> 'profile#show'
  
# devise_for "users", :skip => [:registrations]
#  as :user do
#   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_regsitration'
#   put 'users' => 'devise/registrations#update', :as => 'user_registration'
#  end 
  root 'site#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	
	def show
			@order_items = current_order.order_items
	end

	
	def index
			session.delete(:order_id)
	end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_cart_item.html.erb
<div>
		<div>
			<h3><strong><u>Order Summary:</u></strong></h3>
		    <h5><strong>Order Total: <%="#{current_order.subtotal}"%></strong></h5>
		    <%= button_to 'Go to checkout', payments_path, :method => :get %>
		    </br>
		    <%= button_to 'Empty Cart', carts_index_url(@carts), method: :get, data: { confirm: 'Are you sure you want to empty the cart?' } %>
		</div>
<div class="yellow-surrounding-box">

<% if @order_items.size>0 %>
<table class='catalog'>
  <% @order_items.each do |item| %>
   <tr>
        <td>
          <br>
          <div class='title'>
            <strong><%= item.product.product%></strong>
          </div>
          <div class='description'>
            <%= item.product.description%>
          </div>
          <div class='price'>
            <p><strong>Price: <%= number_to_currency(item.product.price, :unit => '€') %></strong></p>
          </div>
          <br>
            
            <td><div>
         <%= form_for(item, remote: true) do |f| %>
					<%= f.hidden_field :product_id, value: item.product.id %>
					<div class="form-group">
						<%= f.number_field :quantity, value: item.quantity.to_i, min: 1, :maxlength=>"7" %> 
						<br>
					    </div>
			        <%= button_to "Update" %> <% end %>
			          <br>
                  <%= button_to "Delete", item, method: :delete, remote: true %>
				<% end %></br></td>
				</div>
          <% end %>
          </div>
        </tr>
   
</table>          
  </div>        
  <br>

app/views/carts/index.html.erb
<h1>You Cart</h1>
<body>
    <div class="yellow-surrounding-box">
		<h3>Your cart was emptied successfully</h3>
		<p> Please proceed to the products page to continue shopping</p>
		<%= link_to 'Continue Shopping', :controller => :products %>
	</div>
</body>
<br>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>You Cart</h1>
<p>Find the summary of the cart products below: </p>
    <div class="yellow-surrounding-box">

<% if @order_items.size>0 %>
                <div class="cart_item">
	            <%= render "carts/cart_item" %>
	  <% else %>
	  <h3> The cart is Empty</h3>
		<p> Please add some products to proceed</p>
			<%= link_to 'Continue Shopping', :controller => :products %>
		<% end %>
 </div>
	  <div>
	    <% if current_user && current_user.admin? %>
   <%= link_to 'New Product', new_product_path %>
   <% end %>
 </div>
</div>

</br>